### PR TITLE
Added NTLM Security provider compatible with HTTP 3.x Apache library.

### PR DESCRIPTION
**Pull request by ernororive**
This change adds the capability to authenticate with NTLM based REST services.

### CODE REVIEW

**Comment by jpulleman** [comment]
Hi Michel, you are right. The following library should be added to the userlib directory: https://jcifs.samba.org/

I have successfully implemented it (in the cloud) for two customers recently with Erno's code (so great job Erno) and the above library version 1.3.17. Have not done anything with access to a property file, only thing I can think of is that 1.3.18 needs extra access and that's why I've used .17 but I don't remember if that's the case sorry. If you can't find the 1.3.17 version for download, let me know I can supply it to you. Don't seem to be able to add it to the pull request myself.

**Comment by acdickinson** [comment]
Is there any update if or when the added authentication with NTLM based REST services is merged back to the main release?

**Comment by mweststrate** [comment]
Apologies, totally overlooked @jpulleman's earlier messages. I merged the above pull request and it will be part of release 2.1

**Comment by acdickinson** [comment]
Hi @mweststrate, great! Thx.

**Comment by acdickinson** [comment]
@mweststrate any idea when the 2.1 version will be released?

**Comment by mweststrate** [comment]
Released!

**Comment by acdickinson** [comment]
Awesome. Thx!

**Pull request closed without merging**
